# Generated by Django 5.0.1 on 2024-01-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_deighborhoods_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deighborhoods',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='town_id',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='department_id',
            new_name='department',
        ),
    ]
